//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public Brand()
        {
            this.Products = new HashSet<Product>();
            this.Promotions = new HashSet<Promotion>();
            this.ReferralPrograms = new HashSet<ReferralProgram>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> AutoGenerateNo { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string BrandCode { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
        public virtual ICollection<ReferralProgram> ReferralPrograms { get; set; }
    }
}
