//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCard_Point
    {
        public long Id { get; set; }
        public string TransactionId { get; set; }
        public long TransactionDetailId { get; set; }
        public Nullable<long> TotalAmount { get; set; }
        public int PointHistoryId { get; set; }
    }
}
