//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportExportMemberTransLog
    {
        public ImportExportMemberTransLog()
        {
            this.ImportExportMemberTransLogDetails = new HashSet<ImportExportMemberTransLogDetail>();
        }
    
        public long Id { get; set; }
        public string ProcessingBatch { get; set; }
        public Nullable<System.DateTime> ProcessingDateTime { get; set; }
        public Nullable<System.DateTime> LastProcessingDateTime { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string TransactionId { get; set; }
    
        public virtual ICollection<ImportExportMemberTransLogDetail> ImportExportMemberTransLogDetails { get; set; }
    }
}
