//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralPointInTransaction
    {
        public int Id { get; set; }
        public string TransactionId { get; set; }
        public int ReferralCustomerId { get; set; }
        public Nullable<decimal> ReferralPoint { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> PointHistoryId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Point_History Point_History { get; set; }
        public virtual Transaction Transaction { get; set; }
        public virtual User User { get; set; }
    }
}
