//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralProgram
    {
        public int Id { get; set; }
        public int BrandId { get; set; }
        public Nullable<long> MiniPurchaseAmount { get; set; }
        public Nullable<decimal> ReferralPoint { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Brand Brand { get; set; }
    }
}
