//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VipCustomer
    {
        public int ID { get; set; }
        public string CustomerCode { get; set; }
        public System.DateTime LastPaidDate { get; set; }
        public long TwoYearsTotalAmount { get; set; }
        public string ShopCode { get; set; }
        public string MemberType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedUserID { get; set; }
    }
}
